package CORBAApp;


/**
* CORBAApp/_CORBAInterfaceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLApp.idl
* Monday, July 8, 2019 9:34:09 o'clock PM EDT
*/

public class _CORBAInterfaceStub extends org.omg.CORBA.portable.ObjectImpl implements CORBAApp.CORBAInterface
{

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  public String processRequest (String clientID, String eventID, String eventType, int bookingCapacity, String requestType, String newEventID, String newEventType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("processRequest", true);
                $out.write_string (clientID);
                $out.write_string (eventID);
                $out.write_string (eventType);
                $out.write_long (bookingCapacity);
                $out.write_string (requestType);
                $out.write_string (newEventID);
                $out.write_string (newEventType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return processRequest (clientID, eventID, eventType, bookingCapacity, requestType, newEventID, newEventType        );
            } finally {
                _releaseReply ($in);
            }
  } // processRequest

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBAApp/CORBAInterface:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CORBAInterfaceStub
