package CORBAApp;

/**
* CORBAApp/CORBAInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLApp.idl
* Monday, July 8, 2019 9:34:09 o'clock PM EDT
*/

public final class CORBAInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBAApp.CORBAInterface value = null;

  public CORBAInterfaceHolder ()
  {
  }

  public CORBAInterfaceHolder (CORBAApp.CORBAInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBAApp.CORBAInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBAApp.CORBAInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBAApp.CORBAInterfaceHelper.type ();
  }

}
