package CORBAApp;


/**
* CORBAApp/CORBAInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLApp.idl
* Monday, July 8, 2019 9:34:09 o'clock PM EDT
*/

public abstract class CORBAInterfacePOA extends org.omg.PortableServer.Servant
 implements CORBAApp.CORBAInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("shutdown", new java.lang.Integer (0));
    _methods.put ("processRequest", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CORBAApp/CORBAInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 1:  // CORBAApp/CORBAInterface/processRequest
       {
         String clientID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         int bookingCapacity = in.read_long ();
         String requestType = in.read_string ();
         String newEventID = in.read_string ();
         String newEventType = in.read_string ();
         String $result = null;
         $result = this.processRequest (clientID, eventID, eventType, bookingCapacity, requestType, newEventID, newEventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBAApp/CORBAInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CORBAInterface _this() 
  {
    return CORBAInterfaceHelper.narrow(
    super._this_object());
  }

  public CORBAInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CORBAInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CORBAInterfacePOA
