package CORBAApp;


/**
* CORBAApp/CORBAInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLApp.idl
* Monday, July 8, 2019 9:34:09 o'clock PM EDT
*/

public interface CORBAInterfaceOperations 
{
  void shutdown ();
  String processRequest (String clientID, String eventID, String eventType, int bookingCapacity, String requestType, String newEventID, String newEventType);
} // interface CORBAInterfaceOperations
