package CORBAApp;


/**
* CORBAApp/CORBAInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLApp.idl
* Monday, July 8, 2019 9:34:09 o'clock PM EDT
*/

public interface CORBAInterface extends CORBAInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBAInterface
